// <auto-generated />
using System;
using CinemaStock.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CinemaStock.API.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260927223316_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CinemaContentGenre", b =>
                {
                    b.Property<Guid>("CinemaContentsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CinemaGenresId")
                        .HasColumnType("uuid");

                    b.HasKey("CinemaContentsId", "CinemaGenresId");

                    b.HasIndex("CinemaGenresId");

                    b.ToTable("CinemaContentGenre");
                });

            modelBuilder.Entity("CinemaContentTag", b =>
                {
                    b.Property<Guid>("CinemaContentsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CinemaTagsId")
                        .HasColumnType("uuid");

                    b.HasKey("CinemaContentsId", "CinemaTagsId");

                    b.HasIndex("CinemaTagsId");

                    b.ToTable("CinemaContentTag");
                });

            modelBuilder.Entity("CinemaStock.API.Data.Entities.Base.CustomList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CustomLists");
                });

            modelBuilder.Entity("CinemaStock.API.Data.Entities.Base.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("CinemaStock.API.Data.Entities.Base.MediaContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("LocalTitle")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("OriginalTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Picture")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("images/films/default/default-cover.png");

                    b.Property<decimal>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0.0m);

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<int?>("ReleaseFormatId")
                        .HasColumnType("integer");

                    b.Property<string>("SourceInfoFrom")
                        .HasColumnType("text");

                    b.Property<int?>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(4);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseFormatId");

                    b.ToTable("MediaContents");

                    b.HasDiscriminator().HasValue("MediaContent");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CinemaStock.API.Data.Entities.Base.ReleaseFormat", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("FormatName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ReleaseFormat");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            FormatName = "Movie"
                        },
                        new
                        {
                            Id = 1,
                            FormatName = "TV"
                        },
                        new
                        {
                            Id = 2,
                            FormatName = "OVA"
                        },
                        new
                        {
                            Id = 3,
                            FormatName = "ONA"
                        },
                        new
                        {
                            Id = 4,
                            FormatName = "Unknown"
                        });
                });

            modelBuilder.Entity("CinemaStock.API.Data.Entities.Base.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("CinemaStock.API.Data.Entities.Base.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("CinemaStock.API.Data.Entities.Base.UserMediaProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CinemaContentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<Guid?>("MediaContentId")
                        .HasColumnType("uuid");

                    b.Property<string>("MyComment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("OwnRate")
                        .HasColumnType("double precision");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CinemaContentId");

                    b.HasIndex("MediaContentId");

                    b.HasIndex("UserId");

                    b.ToTable("UserMediaProgress");

                    b.HasDiscriminator().HasValue("UserMediaProgress");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CinemaStock.API.Data.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("CinemaStock.API.Data.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DeveloperId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PublisherId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperId");

                    b.HasIndex("PublisherId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("CinemaStock.API.Data.Entities.PlatformOS", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PlatformsOS");
                });

            modelBuilder.Entity("CustomListUserMediaProgress", b =>
                {
                    b.Property<int>("CustomListId")
                        .HasColumnType("integer");

                    b.Property<int>("UserMediaProgressesId")
                        .HasColumnType("integer");

                    b.HasKey("CustomListId", "UserMediaProgressesId");

                    b.HasIndex("UserMediaProgressesId");

                    b.ToTable("CustomListUserMediaProgress");
                });

            modelBuilder.Entity("GameGenre", b =>
                {
                    b.Property<Guid>("GameGenresId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GamesId")
                        .HasColumnType("uuid");

                    b.HasKey("GameGenresId", "GamesId");

                    b.HasIndex("GamesId");

                    b.ToTable("GameGenre");
                });

            modelBuilder.Entity("GamePlatformOS", b =>
                {
                    b.Property<Guid>("GamesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlatformId")
                        .HasColumnType("uuid");

                    b.HasKey("GamesId", "PlatformId");

                    b.HasIndex("PlatformId");

                    b.ToTable("GamePlatformOS");
                });

            modelBuilder.Entity("GameTag", b =>
                {
                    b.Property<Guid>("GameTagsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GamesId")
                        .HasColumnType("uuid");

                    b.HasKey("GameTagsId", "GamesId");

                    b.HasIndex("GamesId");

                    b.ToTable("GameTag");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CinemaStock.API.Data.Entities.CinemaContent", b =>
                {
                    b.HasBaseType("CinemaStock.API.Data.Entities.Base.MediaContent");

                    b.Property<int>("DurationInMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ReleaseStudioId")
                        .HasColumnType("uuid");

                    b.HasIndex("ReleaseStudioId");

                    b.HasDiscriminator().HasValue("CinemaContent");
                });

            modelBuilder.Entity("CinemaStock.API.Data.Entities.Base.UserCinemaProgress", b =>
                {
                    b.HasBaseType("CinemaStock.API.Data.Entities.Base.UserMediaProgress");

                    b.Property<int>("EpisodeStopWatching")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("UserMediaProgress", t =>
                        {
                            t.Property("Status")
                                .HasColumnName("UserCinemaProgress_Status");
                        });

                    b.HasDiscriminator().HasValue("UserCinemaProgress");
                });

            modelBuilder.Entity("CinemaStock.API.Data.Entities.Base.UserGameProgress", b =>
                {
                    b.HasBaseType("CinemaStock.API.Data.Entities.Base.UserMediaProgress");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("UserGameProgress");
                });

            modelBuilder.Entity("CinemaContentGenre", b =>
                {
                    b.HasOne("CinemaStock.API.Data.Entities.CinemaContent", null)
                        .WithMany()
                        .HasForeignKey("CinemaContentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaStock.API.Data.Entities.Base.Genre", null)
                        .WithMany()
                        .HasForeignKey("CinemaGenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CinemaContentTag", b =>
                {
                    b.HasOne("CinemaStock.API.Data.Entities.CinemaContent", null)
                        .WithMany()
                        .HasForeignKey("CinemaContentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaStock.API.Data.Entities.Base.Tag", null)
                        .WithMany()
                        .HasForeignKey("CinemaTagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CinemaStock.API.Data.Entities.Base.CustomList", b =>
                {
                    b.HasOne("CinemaStock.API.Data.Entities.Base.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CinemaStock.API.Data.Entities.Base.MediaContent", b =>
                {
                    b.HasOne("CinemaStock.API.Data.Entities.Base.ReleaseFormat", null)
                        .WithMany("MediaContents")
                        .HasForeignKey("ReleaseFormatId");
                });

            modelBuilder.Entity("CinemaStock.API.Data.Entities.Base.UserMediaProgress", b =>
                {
                    b.HasOne("CinemaStock.API.Data.Entities.CinemaContent", null)
                        .WithMany("UserCinemaProgresses")
                        .HasForeignKey("CinemaContentId");

                    b.HasOne("CinemaStock.API.Data.Entities.Base.MediaContent", "MediaContent")
                        .WithMany()
                        .HasForeignKey("MediaContentId");

                    b.HasOne("CinemaStock.API.Data.Entities.Base.User", "User")
                        .WithMany("MediaProgress")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaContent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CinemaStock.API.Data.Entities.Game", b =>
                {
                    b.HasOne("CinemaStock.API.Data.Entities.Company", "Developer")
                        .WithMany("DevelopedGames")
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CinemaStock.API.Data.Entities.Company", "Publisher")
                        .WithMany("PublishedGames")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Developer");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("CustomListUserMediaProgress", b =>
                {
                    b.HasOne("CinemaStock.API.Data.Entities.Base.CustomList", null)
                        .WithMany()
                        .HasForeignKey("CustomListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaStock.API.Data.Entities.Base.UserMediaProgress", null)
                        .WithMany()
                        .HasForeignKey("UserMediaProgressesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameGenre", b =>
                {
                    b.HasOne("CinemaStock.API.Data.Entities.Base.Genre", null)
                        .WithMany()
                        .HasForeignKey("GameGenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaStock.API.Data.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GamesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GamePlatformOS", b =>
                {
                    b.HasOne("CinemaStock.API.Data.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GamesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaStock.API.Data.Entities.PlatformOS", null)
                        .WithMany()
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameTag", b =>
                {
                    b.HasOne("CinemaStock.API.Data.Entities.Base.Tag", null)
                        .WithMany()
                        .HasForeignKey("GameTagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaStock.API.Data.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GamesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("CinemaStock.API.Data.Entities.Base.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("CinemaStock.API.Data.Entities.Base.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaStock.API.Data.Entities.Base.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("CinemaStock.API.Data.Entities.Base.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CinemaStock.API.Data.Entities.CinemaContent", b =>
                {
                    b.HasOne("CinemaStock.API.Data.Entities.Company", "ReleaseStudio")
                        .WithMany("CinemaContents")
                        .HasForeignKey("ReleaseStudioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ReleaseStudio");
                });

            modelBuilder.Entity("CinemaStock.API.Data.Entities.Base.ReleaseFormat", b =>
                {
                    b.Navigation("MediaContents");
                });

            modelBuilder.Entity("CinemaStock.API.Data.Entities.Base.User", b =>
                {
                    b.Navigation("MediaProgress");
                });

            modelBuilder.Entity("CinemaStock.API.Data.Entities.Company", b =>
                {
                    b.Navigation("CinemaContents");

                    b.Navigation("DevelopedGames");

                    b.Navigation("PublishedGames");
                });

            modelBuilder.Entity("CinemaStock.API.Data.Entities.CinemaContent", b =>
                {
                    b.Navigation("UserCinemaProgresses");
                });
#pragma warning restore 612, 618
        }
    }
}
